### PR TITLE
Avoid super.getter

### LINKED ISSUE #326: textContent getter throws exception
It seems that calling the `textContent` getter throws `Uncaught TypeError: Cannot read property 'length' of undefined`, example code:

HTML:
```
<amp-script layout=container src="script.js">
  <button id="button">Run</button>
  <div id="input">Hello</div>
</amp-script>
```

JS:
```js
document.getElementById('button').addEventListener('click', () => {
  document.getElementById('input').textContent;
});
```

Exception seems to be thrown here:
https://github.com/ampproject/worker-dom/blob/f020b73f10f04d25b67c9d406386f3e14e337292/src/worker-thread/dom/Node.ts#L112

### PR DESCRIPTION
**Pull request by choumx**
Fixes #326. Also fixes bunch of tests for #319 due to Preact browser tests' use of `babel-register`.

#328 fixes the same issue for worker-dom's ES5 output, but not for projects that import the ES6 output and have their own transpilation pipeline (e.g. amphtml). Plus, the spec-compliant Babel transpile is pretty large.

### CODE REVIEW

File: src/worker-thread/dom/Element.ts [hunk 1]
```diff
@@ -185,7 +185,7 @@ export class Element extends ParentNode {
    * @return text from all childNodes.
    */
   get textContent(): string {
-    return super.textContent;
```
Comment (jridgewell) [inline src/worker-thread/dom/Element.ts]: How many other occurrences are there? Seems like we'd need a linter to truly fix this.

Comment (choumx) [reply src/worker-thread/dom/Element.ts]: None, but yea automation would be nice.

Comment (jridgewell) [reply src/worker-thread/dom/Element.ts]: https://astexplorer.net/#/gist/39f577ac5181905df3258b719266ab1a/4430476dcea9304cc467bab9292c1a8091c21b79

**Comment by choumx** [comment]
> would we be able to selectively apply this change only for the small population using transpiled to ES5 code?

Not sure how we can do that without compile-time flags e.g. `#ifdef` or similar.

**Comment by jridgewell** [comment]
If we follow this `getX` convention: https://astexplorer.net/#/gist/1a29fc494a1d985e320004d31df72870/5c59bae1e25b8439b6674dfcbd5a159bff8f24a6

**Comment by kristoferbaxter** [comment]
Justin's approach is what I was suggesting.

File: src/worker-thread/dom/Element.ts (hunk 1 above)
Comment (choumx) [reply src/worker-thread/dom/Element.ts]: #349

**Comment by choumx** [comment]
Good ideas, but do we need to block this PR? Size impact is ~50 bytes. 

Filed #349 for the lint rule and rollup plugin.

**Comment by kristoferbaxter** [comment]
I'm fine with moving along until we can address #349. Do you want to move back to loose mode as well for the `nomodule` output?

**Comment by choumx** [comment]
Either works for me. I think loose mode may generate a smaller `nomodule` output.
